# Generated by Django 4.1.4 on 2023-01-11 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='producer',
            new_name='producers',
        ),
    ]
