# Generated by Django 4.1.4 on 2023-01-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_producer_movie_producers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='film_actor', to='movies.actor', verbose_name='Actors'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='producers',
            field=models.ManyToManyField(related_name='film_producer', to='movies.actor', verbose_name='Producers'),
        ),
    ]
