# Generated by Django 4.1.4 on 2023-01-11 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_actors_alter_movie_producers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='url',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='url',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='url',
            new_name='slug',
        ),
    ]
